### ISSUE TITLE
wrong peer dependency

### ISSUE THREAD

**Issue by joshribakoff** [bcherny/ngimport#11]
using webpack v3 and angular 1.5, doing `yarn add ngimport` brings in angular 1.6 but i expect it to use 1.5, as a result I get "warning tried to load angular 2x" and my app does not run. Using `webpack-bundle-analyzer` package I see it loaded angular 1.5 from `node_modules` and additionally loaded angular 1.6 from `node_modueles/ngimport/node_modules`.

It would seem the devDependency in your package is taking precedence over the peerDependency & thus preventing use in angular 1.5 projects that use yarn and/or webpack.

After some time debugging, I found a workaround by adding this to package.json & running `yarn install` again.
```
"resolutions": {
    "angular": "1.5.11"
  }
```

The yarn docs however say this is an experimental feature that is not fully stable. I would like to be able to use your package without relying on experimental yarn features if possible!

**Comment by bcherny** [comment]
Hi @joshribakoff! Thanks for reporting this.

ngimport's [package.json](https://github.com/bcherny/ngimport/blob/7d3d57d0a9235a70d6270fd19aa72edf2f416f47/package.json#L71) requires a version of Angular compatible with `>=1.5.0`. That's as much as we can do from our end. Beyond that, it's up to your project's package.json and package manager to pull in the best version for your project.

I would try removing your node_modules folder and lockfile, then re-installing all of your project's dependencies. Sometimes your lockfile can get out of date with resolutions that used to be good, but are no longer optimal.

If that doesn't work, I would file an issue in Yarn's issue tracker.
