### ISSUE TITLE
JS examples

### ISSUE THREAD

**Issue by chasedeanda** [bcherny/ngimport#5]
Can you provide the es6 js version of what it would look like making legacy modules work? I need to import a service that depends on $location, but I'm not sure how to achieve that by looking at this TypeScript example.
```
// Contents of fooService.ts:

import {IPromise, module} from 'angular'
export let fooService = undefined

interface FooService {
  foo: () => IPromise<{ data: string }>
}

module('myModule').run(function ($injector) {
  fooService = <FooService>$injector.get('fooService')
})
```

**Comment by bcherny** [comment]
Will add. For reference, since TS is a superset of ES6, you can just remove the weird looking stuff and it will work as expected:

```js
// Contents of fooService.ts:

export let fooService = undefined

module('myModule').run(function ($injector) {
  fooService = $injector.get('fooService')
})
```

**Comment by chasedeanda** [comment]
Thanks for the quick response and example. This helped me understand what I needed to do and I got it working 👍 . Great work on the package, works beautifully!
