### ISSUE TITLE
import module to angular di?

### ISSUE THREAD

**Issue by chiptus** [bcherny/ngimport#9]
I'm trying to use, looks promising.

Should we add the name of the module to our main app module?
e.g:
```
angular.module('app', ['bcherny/ngimport'])
```

or does it happen automatically?

**Comment by bcherny** [comment]
Hi @chiptus! Yes, see the [tests](https://github.com/bcherny/ngimport/blob/fda7dc1ea1db05ca6b20b6cddede9026a78375ff/test.ts#L11). Will add it to the README too.
